name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Replace API key placeholder
        run: |
          mkdir dist
          sed "s|{{WEB3FORMS_API_KEY}}|${{ secrets.WEB3FORMS_API_KEY }}|g" index.html > dist/index.html

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
