name: Deploy static content to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Pages
        uses: actions/configure-pages@v5

      - name: Replace placeholder and prepare site
        run: |
          mkdir dist
          # Replace placeholder with real API key from secret
          sed "s|{{WEB3FORMS_API_KEY}}|${{ secrets.WEB3FORMS_API_KEY }}|g" index.html > dist/index.html
          # Copy additional files (CSS, images, etc. if needed)
          cp -r css dist/ 2>/dev/null || true
          cp -r img dist/ 2>/dev/null || true

          # Add CNAME for custom domain
          # echo "www.apeapothecary.com" > dist/CNAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4



